import { __ } from "@wordpress/i18n";

export const subscriptions = [
	{
		date: 'June 2, 2026',
		email: 'john.doe@gmail.com',
		status: 'Subscribed',
		status_key: 'subscribed',
		reg_user: 'No',
		user_link: '',
		product: 'Classic White Coffee Mug',
		product_id: 3001,
		image: 'https://example.com/uploads/2026/06/product-mug1.jpg',
	},
	{
		date: 'June 5, 2026',
		email: 'sarah.williams@yahoo.com',
		status: 'Subscribed',
		status_key: 'subscribed',
		reg_user: 'Yes',
		user_link: 'https://example.com/users/sarah',
		product: "Father's Day Special Mug",
		product_id: 3002,
		image: 'https://example.com/uploads/2026/06/product-mug2.jpg',
	},
	{
		date: 'June 8, 2026',
		email: 'michael.brown@outlook.com',
		status: 'Mail Sent',
		status_key: 'mailsent',
		reg_user: 'No',
		user_link: '',
		product: 'Personalised Name Mug',
		product_id: 3003,
		image: 'https://example.com/uploads/2026/06/product-mug3.jpg',
	},
	{
		date: 'June 10, 2026',
		email: 'emma.johnson@gmail.com',
		status: 'Subscribed',
		status_key: 'subscribed',
		reg_user: 'No',
		user_link: '',
		product: 'Black Printed Coffee Mug',
		product_id: 3004,
		image: 'https://example.com/uploads/2026/06/product-mug4.jpg',
	},
	{
		date: 'June 12, 2026',
		email: 'alex.smith@test.com',
		status: 'Mail Sent',
		status_key: 'mailsent',
		reg_user: 'Yes',
		user_link: 'https://example.com/users/alex',
		product: "Valentine's Day Special Mug",
		product_id: 3005,
		image: 'https://example.com/uploads/2026/06/product-mug5.jpg',
	},
	{
		date: 'June 14, 2026',
		email: 'olivia.miller@gmail.com',
		status: 'Subscribed',
		status_key: 'subscribed',
		reg_user: 'No',
		user_link: '',
		product: 'Travel Coffee Mug',
		product_id: 3006,
		image: 'https://example.com/uploads/2026/06/product-mug6.jpg',
	},
	{
		date: 'June 16, 2026',
		email: 'david.wilson@test.com',
		status: 'Subscribed',
		status_key: 'subscribed',
		reg_user: 'Yes',
		user_link: 'https://example.com/users/david',
		product: 'Premium Ceramic Mug',
		product_id: 3007,
		image: 'https://example.com/uploads/2026/06/product-mug7.jpg',
	},
	{
		date: 'June 18, 2026',
		email: 'sophia.clark@yahoo.com',
		status: 'Mail Sent',
		status_key: 'mailsent',
		reg_user: 'No',
		user_link: '',
		product: 'Birthday Gift Mug',
		product_id: 3008,
		image: 'https://example.com/uploads/2026/06/product-mug8.jpg',
	},
	{
		date: 'June 20, 2026',
		email: 'james.taylor@gmail.com',
		status: 'Subscribed',
		status_key: 'subscribed',
		reg_user: 'No',
		user_link: '',
		product: 'Minimalist Coffee Cup',
		product_id: 3009,
		image: 'https://example.com/uploads/2026/06/product-mug9.jpg',
	},
	{
		date: 'June 21, 2026',
		email: 'mia.anderson@test.com',
		status: 'Mail Sent',
		status_key: 'mailsent',
		reg_user: 'Yes',
		user_link: 'https://example.com/users/mia',
		product: 'Office Desk Mug',
		product_id: 3010,
		image: 'https://example.com/uploads/2026/06/product-mug10.jpg',
	},
];

export const defaultCategoryCounts = [
	{
		value: 'all',
		label: __('All', 'catalogx-pro'),
		count: 12,
	},
	{
		value: 'subscribed',
		label: __('Subscribed', 'catalogx-pro'),
		count: 9,
	},
	{
		value: 'unsubscribed',
		label: __('Unsubscribed', 'catalogx-pro'),
		count: 0,
	},
	{
		value: 'mailsent',
		label: __('Mail Sent', 'catalogx-pro'),
		count: 3,
	},
];