export const dummyRules = [
    {
        "id": "1",
        "name": "Bulk Order Discount",
        "user_id": null,
        "role_id": "administrator",
        "product_id": "-1",
        "category_id": null,
        "brand_id": null,
        "quantity": "10",
        "type": "percentage",
        "amount": "15",
        "priority": "1",
        "active": "1"
    },
    {
        "id": "2",
        "name": "Editor Brand Offer",
        "user_id": null,
        "role_id": "editor",
        "product_id": null,
        "category_id": null,
        "brand_id": "-1",
        "quantity": "5",
        "type": "fixed",
        "amount": "50",
        "priority": "2",
        "active": "1"
    },
    {
        "id": "3",
        "name": "Category Sale",
        "user_id": null,
        "role_id": "shop_manager",
        "product_id": null,
        "category_id": "12",
        "brand_id": null,
        "quantity": "20",
        "type": "percentage",
        "amount": "25",
        "priority": "3",
        "active": "1"
    },
    {
        "id": "4",
        "name": "Product Launch Offer",
        "user_id": null,
        "role_id": "customer",
        "product_id": "101",
        "category_id": null,
        "brand_id": null,
        "quantity": "2",
        "type": "fixed",
        "amount": "100",
        "priority": "4",
        "active": "1"
    },
    {
        "id": "5",
        "name": "VIP Customer Discount",
        "user_id": "25",
        "role_id": null,
        "product_id": null,
        "category_id": null,
        "brand_id": null,
        "quantity": "15",
        "type": "percentage",
        "amount": "30",
        "priority": "5",
        "active": "1"
    },
    {
        "id": "6",
        "name": "Holiday Mega Sale",
        "user_id": null,
        "role_id": "subscriber",
        "product_id": null,
        "category_id": "8",
        "brand_id": null,
        "quantity": "3",
        "type": "percentage",
        "amount": "10",
        "priority": "6",
        "active": "1"
    },
    {
        "id": "7",
        "name": "Premium Member Offer",
        "user_id": "42",
        "role_id": null,
        "product_id": null,
        "category_id": null,
        "brand_id": null,
        "quantity": "8",
        "type": "fixed",
        "amount": "75",
        "priority": "7",
        "active": "1"
    },
    {
        "id": "8",
        "name": "Fashion Category Discount",
        "user_id": null,
        "role_id": "customer",
        "product_id": null,
        "category_id": "21",
        "brand_id": null,
        "quantity": "4",
        "type": "percentage",
        "amount": "12",
        "priority": "8",
        "active": "0"
    },
    {
        "id": "9",
        "name": "Electronics Flash Deal",
        "user_id": null,
        "role_id": "shop_manager",
        "product_id": "205",
        "category_id": null,
        "brand_id": null,
        "quantity": "1",
        "type": "fixed",
        "amount": "200",
        "priority": "9",
        "active": "1"
    },
    {
        "id": "10",
        "name": "Brand Loyalty Bonus",
        "user_id": null,
        "role_id": null,
        "product_id": null,
        "category_id": null,
        "brand_id": "7",
        "quantity": "6",
        "type": "percentage",
        "amount": "18",
        "priority": "10",
        "active": "1"
    },
    {
        "id": "11",
        "name": "Black Friday Special",
        "user_id": null,
        "role_id": "administrator",
        "product_id": "-1",
        "category_id": null,
        "brand_id": null,
        "quantity": "25",
        "type": "percentage",
        "amount": "40",
        "priority": "11",
        "active": "1"
    },
    {
        "id": "12",
        "name": "Furniture Deal",
        "user_id": null,
        "role_id": "editor",
        "product_id": "310",
        "category_id": null,
        "brand_id": null,
        "quantity": "2",
        "type": "fixed",
        "amount": "120",
        "priority": "12",
        "active": "1"
    },
    {
        "id": "13",
        "name": "Wholesale Discount",
        "user_id": "88",
        "role_id": null,
        "product_id": null,
        "category_id": null,
        "brand_id": null,
        "quantity": "50",
        "type": "percentage",
        "amount": "35",
        "priority": "13",
        "active": "1"
    },
    {
        "id": "14",
        "name": "Sports Collection Offer",
        "user_id": null,
        "role_id": "customer",
        "product_id": null,
        "category_id": "33",
        "brand_id": null,
        "quantity": "7",
        "type": "fixed",
        "amount": "60",
        "priority": "14",
        "active": "0"
    },
    {
        "id": "15",
        "name": "Clearance Stock Discount",
        "user_id": null,
        "role_id": "subscriber",
        "product_id": "450",
        "category_id": null,
        "brand_id": "15",
        "quantity": "12",
        "type": "percentage",
        "amount": "22",
        "priority": "15",
        "active": "1"
    }
];