import AutoGeneratedDefaultInput from "../src/components/AutoGeneratedDefaultInput";

export default {
    title: "Zyra/Components/AutoGeneratedDefaultInput",
    component: AutoGeneratedDefaultInput,
};

export const TestAutoGeneratedDefaultInputInput = () => {
    const AutoGeneratedDefaultInputProps = {
        value: "Initial Value",
        proSetting: true,
        description: "This field is only available in the Pro version.",
        onChange: ( newValue ) => {
            console.log( "Value changed to:", newValue );
        },
    };

    return <AutoGeneratedDefaultInput { ...AutoGeneratedDefaultInputProps } />;
};
