import { __ } from "@wordpress/i18n";

export const dummyProducts = [
	{
		id: 19,
		sku: 'VAR-001',
		name: 'Wireless Headphones',
		type: 'Variable',
		sale_price: '65.00',
		regular_price: '77.00',
		backorders: 'no',
		manage_stock: true,
		status_class: 'instock',
		status: 'In Stock',
		stock_quantity: 25,
		subscriber_no: '',
		variation: [
			{
				id: 20,
				sku: 'VAR-001-A',
				name: 'Headphones - Black',
				type: 'Variation',
				sale_price: '60.00',
				regular_price: '77.00',
				backorders: 'no',
				manage_stock: true,
				status_class: 'instock',
				status: 'In Stock',
				stock_quantity: 10,
				subscriber_no: '',
				parent_product_id: 19,
			},
			{
				id: 21,
				sku: 'VAR-001-B',
				name: 'Headphones - Silver',
				type: 'Variation',
				sale_price: '65.00',
				regular_price: '85.00',
				backorders: 'yes',
				manage_stock: true,
				status_class: 'onbackorder',
				status: 'On backorder',
				stock_quantity: 0,
				subscriber_no: '',
				parent_product_id: 19,
			},
			{
				id: 22,
				sku: 'VAR-001-C',
				name: 'Headphones - Gold',
				type: 'Variation',
				sale_price: '70.00',
				regular_price: '95.00',
				backorders: 'no',
				manage_stock: true,
				status_class: 'outofstock',
				status: 'Out of stock',
				stock_quantity: 0,
				subscriber_no: '',
				parent_product_id: 19,
			},
		],
	},
	{
		id: 18,
		sku: 'SMP-001',
		name: 'Fitness Tracker',
		type: 'Simple',
		sale_price: '45.00',
		regular_price: '777.00',
		backorders: 'no',
		manage_stock: true,
		status_class: 'instock',
		status: 'In Stock',
		stock_quantity: 50,
		subscriber_no: '0',
	},
	{
		id: 17,
		sku: 'SMP-002',
		name: 'Charging Cable',
		type: 'Simple',
		sale_price: '65.00',
		regular_price: '71.00',
		backorders: 'no',
		manage_stock: true,
		status_class: 'instock',
		status: 'In Stock',
		stock_quantity: 100,
		subscriber_no: '1',
	},
	{
		id: 16,
		sku: 'SMP-004',
		name: 'Bluetooth Speaker',
		type: 'Simple',
		sale_price: '45.00',
		regular_price: '89.00',
		backorders: 'yes',
		manage_stock: true,
		status_class: 'onbackorder',
		status: 'On backorder',
		stock_quantity: 0,
		subscriber_no: '0',
	},
	{
		id: 23,
		sku: 'VAR-002',
		name: 'Smart TV',
		type: 'Variable',
		sale_price: '450.00',
		regular_price: '550.00',
		backorders: 'yes',
		manage_stock: true,
		status_class: 'onbackorder',
		status: 'On backorder',
		stock_quantity: 0,
		subscriber_no: '',
		variation: [
			{
				id: 24,
				sku: 'VAR-002-A',
				name: 'Smart TV - 55"',
				type: 'Variation',
				sale_price: '450.00',
				regular_price: '550.00',
				backorders: 'no',
				manage_stock: true,
				status_class: 'instock',
				status: 'In Stock',
				stock_quantity: 5,
				subscriber_no: '',
				parent_product_id: 23,
			},
			{
				id: 25,
				sku: 'VAR-002-B',
				name: 'Smart TV - 65"',
				type: 'Variation',
				sale_price: '650.00',
				regular_price: '750.00',
				backorders: 'yes',
				manage_stock: true,
				status_class: 'onbackorder',
				status: 'On backorder',
				stock_quantity: 0,
				subscriber_no: '',
				parent_product_id: 23,
			},
			{
				id: 26,
				sku: 'VAR-002-C',
				name: 'Smart TV - 75"',
				type: 'Variation',
				sale_price: '850.00',
				regular_price: '950.00',
				backorders: 'no',
				manage_stock: true,
				status_class: 'outofstock',
				status: 'Out of stock',
				stock_quantity: 0,
				subscriber_no: '',
				parent_product_id: 23,
			},
		],
	},
	{
		id: 18,
		sku: 'SMP-001',
		name: 'Fitness Tracker',
		type: 'Simple',
		sale_price: '45.00',
		regular_price: '777.00',
		backorders: 'no',
		manage_stock: true,
		status_class: 'instock',
		status: 'In Stock',
		stock_quantity: 50,
		subscriber_no: '0',
	},
	{
		id: 17,
		sku: 'SMP-002',
		name: 'Charging Cable',
		type: 'Simple',
		sale_price: '65.00',
		regular_price: '71.00',
		backorders: 'no',
		manage_stock: true,
		status_class: 'instock',
		status: 'In Stock',
		stock_quantity: 100,
		subscriber_no: '1',
	},
	{
		id: 16,
		sku: 'SMP-004',
		name: 'Bluetooth Speaker',
		type: 'Simple',
		sale_price: '45.00',
		regular_price: '89.00',
		backorders: 'yes',
		manage_stock: true,
		status_class: 'onbackorder',
		status: 'On backorder',
		stock_quantity: 0,
		subscriber_no: '0',
	},
	{
		id: 15,
		sku: 'SMP-005',
		name: 'Phone Case',
		type: 'Simple',
		sale_price: '15.00',
		regular_price: '29.00',
		backorders: 'no',
		manage_stock: true,
		status_class: 'instock',
		status: 'In Stock',
		stock_quantity: 200,
		subscriber_no: '0',
	},
	{
		id: 14,
		sku: 'SMP-006',
		name: 'Charging Pad',
		type: 'Simple',
		sale_price: '25.00',
		regular_price: '45.00',
		backorders: 'no',
		manage_stock: true,
		status_class: 'outofstock',
		status: 'Out of stock',
		stock_quantity: 0,
		subscriber_no: '0',
	},
	{
		id: 13,
		sku: 'SMP-003',
		name: 'HD Monitor',
		type: 'Simple',
		sale_price: '70.00',
		regular_price: '76.00',
		backorders: 'no',
		manage_stock: true,
		status_class: 'instock',
		status: 'In Stock',
		stock_quantity: 15,
		subscriber_no: '0',
	},
	{
		id: 12,
		sku: 'SMP-007',
		name: 'Office Chair',
		type: 'Simple',
		sale_price: '120.00',
		regular_price: '180.00',
		backorders: 'yes',
		manage_stock: true,
		status_class: 'onbackorder',
		status: 'On backorder',
		stock_quantity: 0,
		subscriber_no: '0',
	},
	{
		id: 11,
		sku: 'SMP-008',
		name: 'Gaming Keyboard',
		type: 'Simple',
		sale_price: '75.00',
		regular_price: '100.00',
		backorders: 'no',
		manage_stock: true,
		status_class: 'outofstock',
		status: 'Out of stock',
		stock_quantity: 0,
		subscriber_no: '0',
	},
];

export const defaultCategoryCounts = [
	{
		value: 'all',
		label: __('All', 'notifima'),
		count: 13,
	},
	{
		value: 'instock',
		label: __('In Stock', 'notifima'),
		count: 7,
	},
	{
		value: 'onbackorder',
		label: __('On Backorder', 'notifima'),
		count: 4,
	},
	{
		value: 'outofstock',
		label: __('Out of Stock', 'notifima'),
		count: 2,
	},
];