export default {
    id: 'special_input',
    priority: 2,
    name: "Special",
    desc: "Set up sales flow and catalog mode with integrated enquiry and quotation management.",
    icon: 'adminLib-settings',
    submitUrl: 'save-settings',
    modal: [
        {
            key: 'separator_content',
            type: 'section',
            desc: "AutoGeneratedDefaultInput",
        },
        {
            key: "sample_ssokey",
            type: "sso-key",
            label: "SSO Secret Key",
        },
        {
            key: 'separator_content',
            type: 'section',
            desc: "CheckboxCustomImg",
        },
        {
            key: "sample_checkbox_custom_img",
            type: "checkbox-custom-img",
            label: "Synchronization flow between sites",
            syncDirections: [
                {
                  value: 'wordpress_to_moodle',
                  label: 'WordPress to Moodle',
                  img1: appLocalizer.wordpress_logo,
                  img2: appLocalizer.moodle_logo
                },
                {
                  value: 'moodle_to_wordpress',
                  label: 'Moodle to WordPress',
                  img1: appLocalizer.moodle_logo,
                  img2: appLocalizer.wordpress_logo
                }
            ],
            proSetting: true,
        },
        {
            key: 'separator_content',
            type: 'section',
            desc: "ConnectButton",
        },
        {
            key: "sample_test_connection",
            type: "testconnection",
            label: "MooWoodle test connection",
            apiLink: '',
            tasks: [
            ],
        },
        {
            key: 'separator_content',
            type: 'section',
            desc: "Log",
        },
        {
            key: "sample_adv_log",
            type: "log",
            classes: "log-section",
            fetchApiLink: "",
            downloadApiLink: "",
            fileName: "error.txt"
        },
        {
            key: 'separator_content',
            type: 'section',
            desc: "MergeComponent",
        },
        {
            key: "sample_mergeComponent",
            type: "mergeComponent",
            label: "sample mergeComponent",
            fields: [
                {
                    name: 'wholesale_discount_type',
                    type: 'select',
                    options: [
                        { 
                            value: 'fixed_amount', 
                            label: 'Fixed Amount' 
                        },
                        { 
                            value: 'percentage_amount', 
                            label: 'Percentage Amount' 
                        }
                    ]
                },
                {
                    name: 'wholesale_amount',
                    type: 'number',
                    placeholder: 'Discount value'
                },
                {
                    name: 'minimum_quantity',
                    type: 'number',
                    placeholder: 'Minimum quantity'
                }
            ],
            desc: '',
            proSetting: true
        },
        {
            key: 'separator_content',
            type: 'section',
            desc: "MultiCheckboxTable",
        },
        {
            key: 'sample_multicheckbox_table',
            type: 'multi-checkbox-table',
            label: "Multicheckbox Table",
            classes: 'gridTable',
            rows: [
                {
                    key: "row1",
                    label:"Download as PDF",
                },
                {
                    key: "row2",
                    label:"Attach with Email",
                },
            ],
            columns: [
                {
                    key: "column1",
                    label: "Enquiry"
                },
                {
                    key: "column2",
                    label: "Quote"
                },
            ],
            proSetting: true
        },
        {
            key: 'separator_content',
            type: 'section',
            desc: "ShortCodeTable",
        },
        {
            key: 'sample_shortCode',
            type: 'shortCode-table',
            label: "shortcode table",
            desc: '',
            optionLabel: [
                'Shortcodes',
                'Description',
            ],
            option: [
                {
                    key: '',
                    label: '[catalog_enquiry_cart]',
                    desc: 'Enables you to create a seller dashboard',
                },
                {
                    key: '',
                    label: '[request_quote]',
                    desc: 'Enables you to create a seller dashboard',
                },
                {
                    key: '',
                    label: '[wholesale_product_list]',
                    desc: 'Enables you to create a seller dashboard',
                },
            ]
        },
        {
            key: 'separator_content',
            type: 'section',
            desc: "SyncMap",
        },
        {
            key: "sample_syncmap",
            type: "sync-map",
            desc: "",
            label: "Profile information mapping",
            select_deselect: true,
            syncFieldsMap: {
                wordpress: {
                  heading: 'WordPress',
                  fields: {
                    firstname: 'First name',
                    lastname: 'Last name',
                    username: 'User name',
                    password: 'Password'
                  }
                },
                moodle: {
                  heading: 'Moodle',
                  fields: {
                    firstname: 'First name',
                    lastname: 'Last name',
                    username: 'User name',
                    password: 'Password'
                  }
                }
            }
        },
        {
            key: 'separator_content',
            type: 'section',
            desc: "SyncNow",
        },
        {
            key: "sample_syncbutton",
            type: "syncbutton",
            interval: 2500,
            apilink: '', //api link
            statusApiLink: '',//status api link
            value: "Synchronize courses now!",
            desc: ""
        },
        {
            key: 'separator_content',
            type: 'section',
            desc: "InputMailchimpList",
        },
        {
            key: "mailchimp_api",
            selectKey: 'selected_mailchimp_list',
            optionKey: 'mailchimp_list_options',
            apiLink: "get-mailchimp-list",
            type: "api-connect",
            label: "Mailchimp API",
        },
        {
            key: 'separator_content',
            type: 'section',
            desc: "FormCustomizer(stock alert form)",
        },
        {
            key: "sample_form",
            type: "stock-alert-form-customizer",
            label: 'Sample Form Customizer', 
        },
        {
            key: 'separator_content',
            type: 'section',
            desc: "ButtonCustomizer",
        },
        {
            key: "sample_btn_customizer",
            type: "button-customizer",
        },       
    ]
}