import { WholesaleUserRow } from "./wholesaleUser";

export const dummyWholesaleUsers: WholesaleUserRow[] = [
	{
		id: 1,
		user: 'John Doe',
		user_email: 'john@example.com',
		status: 'Approved',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 2,
		user: 'Sarah Williams',
		user_email: 'sarah@example.com',
		status: 'Rejected',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 3,
		user: 'Michael Brown',
		user_email: 'michael@example.com',
		status: 'Pending',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 4,
		user: 'Emily Johnson',
		user_email: 'emily@example.com',
		status: 'Approved',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 5,
		user: 'David Miller',
		user_email: 'david@example.com',
		status: 'Approved',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 6,
		user: 'Sophia Wilson',
		user_email: 'sophia@example.com',
		status: 'Refunded',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 7,
		user: 'James Anderson',
		user_email: 'james@example.com',
		status: 'Rejected',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 8,
		user: 'Olivia Taylor',
		user_email: 'olivia@example.com',
		status: 'Approved',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 9,
		user: 'Daniel Thomas',
		user_email: 'daniel@example.com',
		status: 'Rejected',
		date: 'May 12, 2026',
		action: '#',
	},
	{
		id: 10,
		user: 'Emma Martinez',
		user_email: 'emma@example.com',
		status: 'Pending',
		date: 'May 12, 2026',
		action: '#',
	},
];