import { CohortRow } from './Cohort';

export const dummyCohorts: CohortRow[] = [
	{
		id: 1,
		moodle_cohort_id: 1,
		cohort_name: 'Web Development Beginners',
		product_name: 'Web Development Course',
		product_url: '#',
		product_image: '',
		enrolled_user: 18,
		date: 'May 12, 2026',
	},
	{
		id: 2,
		moodle_cohort_id: 2,
		cohort_name: 'Advanced React Training',
		product_name: 'React Masterclass',
		product_url: '#',
		product_image: '',
		enrolled_user: 25,
		date: 'May 12, 2026',
	},
	{
		id: 3,
		moodle_cohort_id: 3,
		cohort_name: 'WordPress Plugin Development',
		product_name: 'WordPress Plugin Course',
		product_url: '#',
		product_image: '',
		enrolled_user: 12,
		date: 'May 12, 2026',
	},
	{
		id: 4,
		moodle_cohort_id: 4,
		cohort_name: 'JavaScript Essentials',
		product_name: 'JavaScript Bootcamp',
		product_url: '#',
		product_image: '',
		enrolled_user: 30,
		date: 'May 12, 2026',
	},
	{
		id: 5,
		moodle_cohort_id: 5,
		cohort_name: 'Full Stack Developer Program',
		product_name: 'Full Stack Course',
		product_url: '#',
		product_image: '',
		enrolled_user: 22,
		date: 'May 12, 2026',
	},
	{
		id: 6,
		moodle_cohort_id: 6,
		cohort_name: 'PHP and Laravel Mastery',
		product_name: 'Laravel Advanced Training',
		product_url: '#',
		product_image: '',
		enrolled_user: 16,
		date: 'May 12, 2026',
	},
	{
		id: 7,
		moodle_cohort_id: 7,
		cohort_name: 'WooCommerce Store Management',
		product_name: 'WooCommerce Expert Course',
		product_url: '#',
		product_image: '',
		enrolled_user: 14,
		date: 'May 12, 2026',
	},
	{
		id: 8,
		moodle_cohort_id: 8,
		cohort_name: 'Modern TypeScript Development',
		product_name: 'TypeScript Fundamentals',
		product_url: '#',
		product_image: '',
		enrolled_user: 20,
		date: 'May 12, 2026',
	},
	{
		id: 9,
		moodle_cohort_id: 9,
		cohort_name: 'REST API Development',
		product_name: 'REST API Engineering',
		product_url: '#',
		product_image: '',
		enrolled_user: 11,
		date: 'May 12, 2026',
	},
	{
		id: 10,
		moodle_cohort_id: 10,
		cohort_name: 'Node.js Backend Architecture',
		product_name: 'Node.js Backend Course',
		product_url: '#',
		product_image: '',
		enrolled_user: 28,
		date: 'May 12, 2026',
	},
];
